'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en' | 'zh' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    nav_home: 'Inicio',
    nav_sales: 'Ventas',
    nav_rentals: 'Rentas',
    nav_about: 'Quiénes Somos',
    nav_contact: 'Contactos',
    hero_title_1: 'Encuentra tu',
    hero_title_2: 'Hogar Ideal',
    hero_title_3: 'en el Soconusco',
    hero_subtitle: 'Descubre las mejores propiedades en venta y renta. Tu próxima inversión comienza aquí.',
    btn_properties: 'Ver Propiedades',
    btn_contact: 'Contáctanos',
    stats_sold: 'Propiedades Vendidas',
    stats_years: 'Años de Experiencia',
    stats_clients: 'Clientes Felices',
    stats_deals: 'Tratos Cerrados',
    featured_title: 'Propiedades Destacadas',
    featured_subtitle: 'Oportunidades Exclusivas',
    view_all: 'Ver todas las propiedades',
    footer_desc: 'Tu mejor opción para encontrar el hogar de tus sueños o la inversión perfecta en la región del Soconusco.',
    footer_links: 'Enlaces Rápidos',
    footer_contact: 'Contáctanos',
    footer_follow: 'Síguenos',
    footer_rights: 'Todos los derechos reservados.',
    filter_title: 'Filtrar Propiedades',
    filter_min: 'Precio Mínimo',
    filter_max: 'Precio Máximo',
    filter_btn: 'Filtrar',
    filter_clear: 'Limpiar',
    filter_show: 'Toca para mostrar filtros',
    filter_hide: 'Toca para ocultar filtros',
    filter_by_price: 'Filtrar por Precio',
    filter_placeholder_min: 'Ej. 1000000',
    filter_placeholder_max: 'Ej. 5000000',
    contact_title: 'Contáctanos',
    contact_subtitle: 'Estamos aquí para ayudarte a encontrar tu propiedad ideal o vender la tuya al mejor precio.',
    contact_location: 'Ubicación',
    contact_phone: 'Teléfono',
    contact_schedule: 'Horario',
    form_name: 'Nombre completo *',
    form_email: 'Correo electrónico',
    form_phone: 'Teléfono',
    form_message: 'Mensaje',
    form_send: 'Enviar mensaje',
    form_sending: 'Enviando...',
    form_success_title: '¡Gracias!',
    form_success_msg: 'Hemos recibido tus datos. Te contactaremos pronto.',
    contact_interested: '¿Te interesa esta propiedad?',
    contact_leave_data: 'Déjanos tus datos y un asesor se pondrá en contacto contigo a la brevedad.',
    contact_send_another: 'Enviar otro mensaje',
    contact_placeholder_name: 'Tu nombre',
    contact_placeholder_email: 'ejemplo@correo.com',
    contact_placeholder_phone: '10 dígitos',
    contact_placeholder_msg_prop: 'Hola, me interesa esta propiedad...',
    contact_placeholder_msg_gen: 'Hola, me gustaría recibir más información...',
    contact_send_interest: 'Enviar interés',
    contact_error_submit: 'Hubo un problema al enviar tu mensaje. Por favor intenta de nuevo.',
    contact_error_generic: 'Error al enviar el formulario',
    card_no_image: 'Sin Imagen',
    card_sale: 'Venta',
    card_rent: 'Renta',
    card_sold: 'VENDIDA',
    card_rented: 'RENTADA',
    card_bedrooms: 'Hab',
    card_bathrooms: 'Baños',
    card_view_details: 'Ver Detalles',
    contact_info_title: 'Información de Contacto',
    contact_schedule_days: 'Lunes - Viernes: 9:00 AM - 6:00 PM',
    contact_schedule_sat: 'Sábado: 9:00 AM - 2:00 PM',
    contact_whatsapp_btn: 'Enviar WhatsApp',
    contact_ready_publish: '¿Listo para publicar?',
    contact_join_network: 'Únete a nuestra red y llega a miles de compradores potenciales hoy mismo.',
    contact_contact_advisor: 'Contactar Asesor',
    contact_send_message_title: 'Envíanos un Mensaje',
    contact_send_message_desc: 'Completa el formulario y nos pondremos en contacto contigo a la brevedad.',
    about_title: 'Quiénes Somos',
    about_subtitle: 'Conoce la historia y los valores que nos impulsan a ser líderes en el mercado inmobiliario.',
    about_essence: 'Nuestra Esencia',
    about_main_title: 'Construyendo Confianza, Creando Hogares',
    about_description: 'Inmobiliaria Soconusco nació con la visión de transformar el mercado inmobiliario en la región. Con años de experiencia conectando a familias con sus hogares ideales, nos hemos consolidado como líderes en confianza y servicio personalizado. Entendemos que cada propiedad cuenta una historia y cada cliente tiene un sueño.',
    about_value_1_title: 'Profesionalismo',
    about_value_1_desc: 'Equipo experto dedicado a brindarte la mejor asesoría en cada paso.',
    about_value_2_title: 'Compromiso',
    about_value_2_desc: 'Tu satisfacción es nuestra prioridad. Nos comprometemos con tus objetivos.',
    about_value_3_title: 'Innovación',
    about_value_3_desc: 'Utilizamos las últimas tecnologías para destacar tu propiedad.',
    about_why_title: '¿Por qué elegirnos?',
    about_why_1: 'Amplio catálogo de propiedades verificadas.',
    about_why_2: 'Asesoría legal y financiera experta.',
    about_why_3: 'Trato directo, humano y personalizado.',
    about_why_4: 'Marketing digital avanzado para tu inmueble.',
    about_why_5: 'Acompañamiento hasta la firma de escrituras.',
    sales_title: 'Propiedades en Venta',
    sales_subtitle: 'Explora nuestra selección exclusiva de propiedades disponibles para la venta en la región del Soconusco.',
    rentals_title: 'Propiedades en Renta',
    rentals_subtitle: 'Encuentra el lugar perfecto para vivir o establecer tu negocio en renta.',
    no_properties_found: 'No se encontraron propiedades',
    try_adjusting_filters: 'Intenta ajustar los filtros de búsqueda.',
    prop_back_home: 'Volver al inicio',
    prop_description: 'Descripción',
    prop_features: 'Características',
    prop_location: 'Ubicación',
    prop_video: 'Video Recorrido',
    prop_nearby: 'Lugares Cercanos',
    prop_contact_agent: 'Contactar Agente',
    prop_price: 'Precio',
    prop_type: 'Tipo',
    prop_status: 'Estado',
    prop_contact_owner: 'Contactar al Propietario',
    prop_location_nearby: 'Ubicación y lugares cercanos',
    prop_virtual_tour: 'Recorrido Virtual',
    prop_video_title: 'Video del Inmueble',
    prop_360_title: 'Vista 360°',
    all_properties_title: 'Todas las Propiedades',
    all_properties_subtitle: 'Explora nuestro catálogo completo de propiedades disponibles.',
    map_no_places: 'Aún no se han registrado lugares cercanos para esta propiedad.',
    map_walking: 'caminando',
    map_meters: 'm',
  },
  en: {
    nav_home: 'Home',
    nav_sales: 'Sales',
    nav_rentals: 'Rentals',
    nav_about: 'About Us',
    nav_contact: 'Contact',
    hero_title_1: 'Find your',
    hero_title_2: 'Ideal Home',
    hero_title_3: 'in Soconusco',
    hero_subtitle: 'Discover the best properties for sale and rent. Your next investment starts here.',
    btn_properties: 'View Properties',
    btn_contact: 'Contact Us',
    stats_sold: 'Properties Sold',
    stats_years: 'Years of Experience',
    stats_clients: 'Happy Clients',
    stats_deals: 'Deals Closed',
    featured_title: 'Featured Properties',
    featured_subtitle: 'Exclusive Opportunities',
    view_all: 'View all properties',
    footer_desc: 'Your best option to find the home of your dreams or the perfect investment in the Soconusco region.',
    footer_links: 'Quick Links',
    footer_contact: 'Contact Us',
    footer_follow: 'Follow Us',
    footer_rights: 'All rights reserved.',
    filter_title: 'Filter Properties',
    filter_min: 'Min Price',
    filter_max: 'Max Price',
    filter_btn: 'Filter',
    filter_clear: 'Clear',
    filter_show: 'Tap to show filters',
    filter_hide: 'Tap to hide filters',
    filter_by_price: 'Filter by Price',
    filter_placeholder_min: 'Ex. 1000000',
    filter_placeholder_max: 'Ex. 5000000',
    contact_title: 'Contact Us',
    contact_subtitle: 'We are here to help you find your ideal property or sell yours at the best price.',
    contact_location: 'Location',
    contact_phone: 'Phone',
    contact_schedule: 'Schedule',
    form_name: 'Full Name *',
    form_email: 'Email',
    form_phone: 'Phone',
    form_message: 'Message',
    form_send: 'Send Message',
    form_sending: 'Sending...',
    form_success_title: 'Thank you!',
    form_success_msg: 'We have received your details. We will contact you soon.',
    contact_interested: 'Interested in this property?',
    contact_leave_data: 'Leave us your details and an advisor will contact you shortly.',
    contact_send_another: 'Send another message',
    contact_placeholder_name: 'Your name',
    contact_placeholder_email: 'example@email.com',
    contact_placeholder_phone: '10 digits',
    contact_placeholder_msg_prop: 'Hello, I am interested in this property...',
    contact_placeholder_msg_gen: 'Hello, I would like to receive more information...',
    contact_send_interest: 'Send interest',
    contact_error_submit: 'There was a problem sending your message. Please try again.',
    contact_error_generic: 'Error sending form',
    card_no_image: 'No Image',
    card_sale: 'Sale',
    card_rent: 'Rent',
    card_sold: 'SOLD',
    card_rented: 'RENTED',
    card_bedrooms: 'Beds',
    card_bathrooms: 'Baths',
    card_view_details: 'View Details',
    contact_info_title: 'Contact Information',
    contact_schedule_days: 'Monday - Friday: 9:00 AM - 6:00 PM',
    contact_schedule_sat: 'Saturday: 9:00 AM - 2:00 PM',
    contact_whatsapp_btn: 'Send WhatsApp',
    contact_ready_publish: 'Ready to publish?',
    contact_join_network: 'Join our network and reach thousands of potential buyers today.',
    contact_contact_advisor: 'Contact Advisor',
    contact_send_message_title: 'Send us a Message',
    contact_send_message_desc: 'Complete the form and we will contact you shortly.',
    about_title: 'About Us',
    about_subtitle: 'Learn about the history and values that drive us to be leaders in the real estate market.',
    about_essence: 'Our Essence',
    about_main_title: 'Building Trust, Creating Homes',
    about_description: 'Inmobiliaria Soconusco was born with the vision of transforming the real estate market in the region. With years of experience connecting families with their ideal homes, we have established ourselves as leaders in trust and personalized service. We understand that every property tells a story and every client has a dream.',
    about_value_1_title: 'Professionalism',
    about_value_1_desc: 'Expert team dedicated to providing you with the best advice at every step.',
    about_value_2_title: 'Commitment',
    about_value_2_desc: 'Your satisfaction is our priority. We are committed to your goals.',
    about_value_3_title: 'Innovation',
    about_value_3_desc: 'We use the latest technologies to highlight your property.',
    about_why_title: 'Why Choose Us?',
    about_why_1: 'Wide catalog of verified properties.',
    about_why_2: 'Expert legal and financial advice.',
    about_why_3: 'Direct, human, and personalized treatment.',
    about_why_4: 'Advanced digital marketing for your property.',
    about_why_5: 'Accompaniment until the signing of deeds.',
    sales_title: 'Properties for Sale',
    sales_subtitle: 'Explore our exclusive selection of properties available for sale in the Soconusco region.',
    rentals_title: 'Properties for Rent',
    rentals_subtitle: 'Find the perfect place to live or establish your business for rent.',
    no_properties_found: 'No properties found',
    try_adjusting_filters: 'Try adjusting the search filters.',
    prop_back_home: 'Back to Home',
    prop_description: 'Description',
    prop_features: 'Features',
    prop_location: 'Location',
    prop_video: 'Video Tour',
    prop_nearby: 'Nearby Places',
    prop_contact_agent: 'Contact Agent',
    prop_price: 'Price',
    prop_type: 'Type',
    prop_status: 'Status',
    prop_contact_owner: 'Contact Owner',
    prop_location_nearby: 'Location and Nearby Places',
    prop_virtual_tour: 'Virtual Tour',
    prop_video_title: 'Property Video',
    prop_360_title: '360° View',
    all_properties_title: 'All Properties',
    all_properties_subtitle: 'Explore our complete catalog of available properties.',
    map_no_places: 'No nearby places registered for this property yet.',
    map_walking: 'walking',
    map_meters: 'm',
  },
  zh: {
    nav_home: '首页',
    nav_sales: '销售',
    nav_rentals: '出租',
    nav_about: '关于我们',
    nav_contact: '联系方式',
    hero_title_1: '在索科努斯科找到您的',
    hero_title_2: '理想家园',
    hero_title_3: '',
    hero_subtitle: '发现最佳的待售和待租物业。您的下一笔投资从这里开始。',
    btn_properties: '查看物业',
    btn_contact: '联系我们',
    stats_sold: '已售物业',
    stats_years: '多年经验',
    stats_clients: '满意的客户',
    stats_deals: '成交交易',
    featured_title: '精选物业',
    featured_subtitle: '独家机会',
    view_all: '查看所有物业',
    footer_desc: '您在索科努斯科地区寻找梦想家园或完美投资的最佳选择。',
    footer_links: '快速链接',
    footer_contact: '联系我们',
    footer_follow: '关注我们',
    footer_rights: '版权所有。',
    filter_title: '筛选物业',
    filter_min: '最低价格',
    filter_max: '最高价格',
    filter_btn: '筛选',
    filter_clear: '清除',
    filter_show: '点击显示筛选',
    filter_hide: '点击隐藏筛选',
    filter_by_price: '按价格筛选',
    filter_placeholder_min: '例如 1000000',
    filter_placeholder_max: '例如 5000000',
    contact_title: '联系我们',
    contact_subtitle: '我们在这里帮助您找到理想的物业或以最优惠的价格出售您的物业。',
    contact_location: '位置',
    contact_phone: '电话',
    contact_schedule: '时间表',
    form_name: '全名 *',
    form_email: '电子邮件',
    form_phone: '电话',
    form_message: '信息',
    form_send: '发送信息',
    form_sending: '发送中...',
    form_success_title: '谢谢！',
    form_success_msg: '我们已收到您的详细信息。我们将尽快与您联系。',
    contact_interested: '对这处房产感兴趣？',
    contact_leave_data: '留下您的详细信息，顾问将很快与您联系。',
    contact_send_another: '发送另一条消息',
    contact_placeholder_name: '您的名字',
    contact_placeholder_email: 'example@email.com',
    contact_placeholder_phone: '10位数字',
    contact_placeholder_msg_prop: '您好，我对这处房产感兴趣...',
    contact_placeholder_msg_gen: '您好，我想了解更多信息...',
    contact_send_interest: '发送意向',
    contact_error_submit: '发送消息时出现问题。请重试。',
    contact_error_generic: '发送表单错误',
    card_no_image: '无图片',
    card_sale: '出售',
    card_rent: '出租',
    card_sold: '已售',
    card_rented: '已租',
    card_bedrooms: '卧室',
    card_bathrooms: '浴室',
    card_view_details: '查看详情',
    contact_info_title: '联系信息',
    contact_schedule_days: '周一 - 周五: 9:00 AM - 6:00 PM',
    contact_schedule_sat: '周六: 9:00 AM - 2:00 PM',
    contact_whatsapp_btn: '发送 WhatsApp',
    contact_ready_publish: '准备发布？',
    contact_join_network: '加入我们的网络，立即接触成千上万的潜在买家。',
    contact_contact_advisor: '联系顾问',
    contact_send_message_title: '给我们发信息',
    contact_send_message_desc: '填写表格，我们将尽快与您联系。',
    about_title: '关于我们',
    about_subtitle: '了解推动我们成为房地产市场领导者的历史和价值观。',
    about_essence: '我们的本质',
    about_main_title: '建立信任，创造家园',
    about_description: 'Soconusco 房地产公司的诞生愿景是改变该地区的房地产市场。凭借多年将家庭与理想家园联系起来的经验，我们已确立了自己在信任和个性化服务方面的领导地位。我们明白每一处房产都有一个故事，每一位客户都有一个梦想。',
    about_value_1_title: '专业精神',
    about_value_1_desc: '专家团队致力于在每一步为您提供最佳建议。',
    about_value_2_title: '承诺',
    about_value_2_desc: '您的满意是我们的首要任务。我们致力于实现您的目标。',
    about_value_3_title: '创新',
    about_value_3_desc: '我们使用最新技术来突出您的房产。',
    about_why_title: '为什么选择我们？',
    about_why_1: '广泛的经过验证的房产目录。',
    about_why_2: '专业的法律和财务建议。',
    about_why_3: '直接、人性化和个性化的待遇。',
    about_why_4: '为您房产提供的高级数字营销。',
    about_why_5: '全程陪伴直至签署契约。',
    sales_title: '待售物业',
    sales_subtitle: '探索我们在索科努斯科地区独家精选的待售物业。',
    rentals_title: '待租物业',
    rentals_subtitle: '寻找完美的居住地或建立您的租赁业务。',
    no_properties_found: '未找到物业',
    try_adjusting_filters: '尝试调整搜索筛选器。',
    prop_back_home: '返回首页',
    prop_description: '描述',
    prop_features: '特征',
    prop_location: '位置',
    prop_video: '视频游览',
    prop_nearby: '附近地点',
    prop_contact_agent: '联系代理',
    prop_price: '价格',
    prop_type: '类型',
    prop_status: '状态',
    prop_contact_owner: '联系业主',
    prop_location_nearby: '位置和附近地点',
    prop_virtual_tour: '虚拟游览',
    prop_video_title: '物业视频',
    prop_360_title: '360° 视图',
    all_properties_title: '所有房产',
    all_properties_subtitle: '探索我们完整的可用房产目录。',
    map_no_places: '此房产尚未注册附近的地点。',
    map_walking: '步行',
    map_meters: '米',
  },
  ru: {
    nav_home: 'Главная',
    nav_sales: 'Продажи',
    nav_rentals: 'Аренда',
    nav_about: 'О нас',
    nav_contact: 'Контакты',
    hero_title_1: 'Найдите свой',
    hero_title_2: 'Идеальный Дом',
    hero_title_3: 'в Соконуско',
    hero_subtitle: 'Откройте для себя лучшую недвижимость на продажу и в аренду. Ваша следующая инвестиция начинается здесь.',
    btn_properties: 'Посмотреть недвижимость',
    btn_contact: 'Связаться с нами',
    stats_sold: 'Продано объектов',
    stats_years: 'Лет опыта',
    stats_clients: 'Счастливых клиентов',
    stats_deals: 'Закрытых сделок',
    featured_title: 'Избранная недвижимость',
    featured_subtitle: 'Эксклюзивные возможности',
    view_all: 'Посмотреть все',
    footer_desc: 'Ваш лучший выбор для поиска дома мечты или идеальной инвестиции в регионе Соконуско.',
    footer_links: 'Быстрые ссылки',
    footer_contact: 'Связаться с нами',
    footer_follow: 'Подписывайтесь',
    footer_rights: 'Все права защищены.',
    filter_title: 'Фильтр недвижимости',
    filter_min: 'Мин. цена',
    filter_max: 'Макс. цена',
    filter_btn: 'Фильтр',
    filter_clear: 'Очистить',
    filter_show: 'Нажмите, чтобы показать фильтры',
    filter_hide: 'Нажмите, чтобы скрыть фильтры',
    filter_by_price: 'Фильтр по цене',
    filter_placeholder_min: 'Напр. 1000000',
    filter_placeholder_max: 'Напр. 5000000',
    contact_title: 'Связаться с нами',
    contact_subtitle: 'Мы здесь, чтобы помочь вам найти идеальную недвижимость или продать вашу по лучшей цене.',
    contact_location: 'Местоположение',
    contact_phone: 'Телефон',
    contact_schedule: 'График работы',
    form_name: 'Полное имя *',
    form_email: 'Электронная почта',
    form_phone: 'Телефон',
    form_message: 'Сообщение',
    form_send: 'Отправить сообщение',
    form_sending: 'Отправка...',
    form_success_title: 'Спасибо!',
    form_success_msg: 'Мы получили ваши данные. Мы свяжемся с вами в ближайшее время.',
    contact_interested: 'Заинтересованы в этой недвижимости?',
    contact_leave_data: 'Оставьте свои данные, и консультант свяжется с вами в ближайшее время.',
    contact_send_another: 'Отправить еще одно сообщение',
    contact_placeholder_name: 'Ваше имя',
    contact_placeholder_email: 'example@email.com',
    contact_placeholder_phone: '10 цифр',
    contact_placeholder_msg_prop: 'Здравствуйте, меня интересует эта недвижимость...',
    contact_placeholder_msg_gen: 'Здравствуйте, я хотел бы получить больше информации...',
    contact_send_interest: 'Отправить интерес',
    contact_error_submit: 'Возникла проблема при отправке сообщения. Пожалуйста, попробуйте снова.',
    contact_error_generic: 'Ошибка отправки формы',
    card_no_image: 'Нет фото',
    card_sale: 'Продажа',
    card_rent: 'Аренда',
    card_sold: 'ПРОДАНО',
    card_rented: 'СДАНО',
    card_bedrooms: 'Спальни',
    card_bathrooms: 'Ванные',
    card_view_details: 'Подробнее',
    contact_info_title: 'Контактная информация',
    contact_schedule_days: 'Понедельник - Пятница: 9:00 AM - 6:00 PM',
    contact_schedule_sat: 'Суббота: 9:00 AM - 2:00 PM',
    contact_whatsapp_btn: 'Отправить WhatsApp',
    contact_ready_publish: 'Готовы опубликовать?',
    contact_join_network: 'Присоединяйтесь к нашей сети и охватите тысячи потенциальных покупателей уже сегодня.',
    contact_contact_advisor: 'Связаться с консультантом',
    contact_send_message_title: 'Отправьте нам сообщение',
    contact_send_message_desc: 'Заполните форму, и мы свяжемся с вами в ближайшее время.',
    about_title: 'О нас',
    about_subtitle: 'Узнайте об истории и ценностях, которые делают нас лидерами на рынке недвижимости.',
    about_essence: 'Наша Суть',
    about_main_title: 'Строим Доверие, Создаем Дома',
    about_description: 'Inmobiliaria Soconusco родилась с видением трансформации рынка недвижимости в регионе. Имея многолетний опыт соединения семей с их идеальными домами, мы зарекомендовали себя как лидеры в области доверия и персонализированного обслуживания. Мы понимаем, что у каждой недвижимости есть история, а у каждого клиента — мечта.',
    about_value_1_title: 'Профессионализм',
    about_value_1_desc: 'Команда экспертов, готовая предоставить вам лучшие советы на каждом этапе.',
    about_value_2_title: 'Обязательство',
    about_value_2_desc: 'Ваше удовлетворение — наш приоритет. Мы привержены вашим целям.',
    about_value_3_title: 'Инновации',
    about_value_3_desc: 'Мы используем новейшие технологии, чтобы выделить вашу недвижимость.',
    about_why_title: 'Почему выбирают нас?',
    about_why_1: 'Широкий каталог проверенной недвижимости.',
    about_why_2: 'Экспертные юридические и финансовые консультации.',
    about_why_3: 'Прямое, человеческое и персонализированное отношение.',
    about_why_4: 'Продвинутый цифровой маркетинг для вашей недвижимости.',
    about_why_5: 'Сопровождение до подписания документов.',
    sales_title: 'Недвижимость на продажу',
    sales_subtitle: 'Изучите нашу эксклюзивную подборку недвижимости, доступной для продажи в регионе Соконуско.',
    rentals_title: 'Недвижимость в аренду',
    rentals_subtitle: 'Найдите идеальное место для жизни или создания бизнеса в аренду.',
    no_properties_found: 'Недвижимость не найдена',
    try_adjusting_filters: 'Попробуйте изменить фильтры поиска.',
    prop_back_home: 'Вернуться на главную',
    prop_description: 'Описание',
    prop_features: 'Особенности',
    prop_location: 'Местоположение',
    prop_video: 'Видеотур',
    prop_nearby: 'Близлежащие места',
    prop_contact_agent: 'Связаться с агентом',
    prop_price: 'Цена',
    prop_type: 'Тип',
    prop_status: 'Статус',
    prop_contact_owner: 'Связаться с владельцем',
    prop_location_nearby: 'Местоположение и близлежащие места',
    prop_virtual_tour: 'Виртуальный тур',
    prop_video_title: 'Видео недвижимости',
    prop_360_title: '360° Вид',
    all_properties_title: 'Все объекты',
    all_properties_subtitle: 'Изучите наш полный каталог доступной недвижимости.',
    map_no_places: 'Для этого объекта пока не зарегистрировано близлежащих мест.',
    map_walking: 'пешком',
    map_meters: 'м',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['es', 'en', 'zh', 'ru'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    const langData = translations[language] as Record<string, string>;
    return langData[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
